apiVersion: v1
kind: Secret
metadata:
  name: storage-config
stringData:
  localMinIO: |
    {
      "type": "s3",
      "access_key_id": "password",
      "secret_access_key": "password",
      "endpoint_url": "http://minio.minio.svc:9000",
      "default_bucket": "modelmesh-example-models",
      "region": "us-south"
    }
