apiVersion: v1
kind: Secret
metadata:
  name: storage-config
stringData:
  aws-connection-localminio: |
    {
      "type": "s3",
      "access_key_id": "admin",
      "secret_access_key": "password",
      "endpoint_url": "http://minio.minio.svc:9000",
      "default_bucket": "modelmesh-example-models",
      "bucket": "modelmesh-example-models",
      "region": "us-east-2"
    }