apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    serving.knative.openshift.io/enablePassthrough: "true"
    sidecar.istio.io/inject: "true"
    sidecar.istio.io/rewriteAppHTTPProbers: "true"
  name: kserve-tritonserver-onnx-mnist
spec:
  predictor:
    serviceAccountName: sa
    model:
      modelFormat:
        name: onnx
      runtime: kserve-tritonserver
      storageUri: s3://modelmesh-example-models/iris.onnx